### ISSUE TITLE
UNRAR 6.0 not supported

### ISSUE THREAD

**Issue by kobbra** [linuxserver/docker-couchpotato#57]
Hi

seems like unrar in baseimage was updated to v6 but couchpotato code only support v4 or v5

"Unsupported RAR version, expected 4.x or 5.x, found: 6.00"

Im getting this error now when trying to unrar a movie.

**Comment by matthewcky2k** [comment]
Same problem here any eta on a fix?

**Comment by blade2005** [comment]
Fuck, this explains why it's been broken for so long.

**Comment by aptalca** [comment]
Honestly, this image probably should have been deprecated a long time ago, but because it still somewhat works, we kept it. It's python2, which is long deprecated. Alpine dropped support for all python2 things except for the core python2 package, which is what's keeping this going. At this point, it's only here for the few people still using it, and because it doesn't cause much maintenance burden for us.

CP itself has been semi-abandoned for years now. We highly recommend moving over to radarr.

**Comment by blade2005** [comment]
I found radarr to perform poorly with me. Though maybe I should give it another go. I recall it breaking on importing my media to it's DB.

**Comment by kobbra** [comment]
i made the switch to radarr because of this issue and haven't looked back since...
